[package]
name = "errori"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#mi basta 1.0 --> per incorporare tutte le versioni successive
thiserror = "1.0"

